version: "3.9"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=D@afFKFTwLHqvJ
      - MYSQL_DATABASE=swapi
      - MYSQL_USER=master
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
